name: CodeTwelve-iOS-UIKit
options:
  bundleIdPrefix: com.codetwelve
  deploymentTarget:
    iOS: 14.0

targets:
  # Main App Target
  CodeTwelve-iOS-UIKit:
    type: application
    platform: iOS
    sources:
      - path: CodeTwelve-iOS-UIKit
    settings:
      base:
        INFOPLIST_FILE: CodeTwelve-iOS-UIKit/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.codetwelve.ios.uikit
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
    info:
      path: CodeTwelve-iOS-UIKit/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: 6.0
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: 1.0
        CFBundleVersion: 1
        UIApplicationSupportsIndirectInputEvents: true

  # UI Library Framework Target
  CodetwelveUI:
    type: framework
    platform: iOS
    sources:
      - path: Sources/CodetwelveUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.codetwelve.uikit
        PRODUCT_NAME: CodetwelveUI
        GENERATE_INFOPLIST_FILE: YES

  # Example App Target
  CodeTwelveExamples:
    type: application
    platform: iOS
    sources:
      - path: Examples/CodeTwelveExamples
    dependencies:
      - target: CodetwelveUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.codetwelve.examples
        PRODUCT_NAME: CodeTwelveExamples
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: Examples/CodeTwelveExamples/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: ""

  # Tests Target
  CodetwelveUITests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/CodetwelveUITests
    dependencies:
      - target: CodetwelveUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.codetwelve.uikit.tests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  CodeTwelve-iOS-UIKit:
    build:
      targets:
        CodeTwelve-iOS-UIKit: all
    run:
      config: Debug

  CodetwelveUI:
    build:
      targets:
        CodetwelveUI: all
    test:
      targets:
        - CodetwelveUITests
      gatherCoverageData: true

  CodeTwelveExamples:
    build:
      targets:
        CodeTwelveExamples: all
    run:
      config: Debug 